apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://localhost:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: prometheus
        tags: ["service"]
        mappedTags:
          - key: "service.name"
            value: "service"
        filterByTraceID: true
        filterBySpanID: true
